name: 'CI Security Checks'
description: 'A list software security checks run as a composite Github action'

on:
  workflow_call:
    inputs:
      sast-scan-flag:
        description: 'Enable Semgrep SAST scanning'
        default: true
      semgrep-timeout:
        description: 'Scan timeout in seconds'
        default: 300
      dependency-license-check-flag:
        description: 'Enable depedency licence check'
        default: true
      dependency-check-config-file:
        description: 'The name and path of your dependency check configuration file'
        default: "dependency-check-config.yml"
      repository:
        description: 'The name of the source repository'
        default: ""
    secrets:
      semgrep-app-token:
        description: 'You semgrep APP token taken from Semgrep App > Settings'
        required: true
jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.semgrep-app-token }}
