name: 'CI Security Checks'
description: 'A list of common open-source software security checks run as a composite Github action'
inputs:
  container-scan-flag:
    description: 'Enable anchore container image scanning'
    default: false
  container-dockerfile:
    description: 'Location of your dockerfile'
    default: ""
  anchore-results-file:
    description: 'The Anchore results file name and path'
    default: "results.json"
  anchore-severity-threshold:
    description: 'The Ancshore severitiy threshold you want to include in your report'
    default: "medium"
  anchore-fail-build:
    description: 'Fail build if severity threshold vulnerabilities are found'
    default: false
  sast-scan-flag:
    description: 'Enable Semgrep SAST scanning'
    default: true
  semgrep-app-token:
    description: 'You semgrep APP token taken from Semgrep App > Settings'
    default: ""
  semgrep-timeout:
    description: 'Scan timeout in seconds'
    default: 300
runs:
  using: "composite"
  jobs:

    anchore-scan:
      if: ${{ github.event.inputs.container-scan-flag }} == true
      name: Anchore Container Image Vulnerability Scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: build local container
          uses: docker/build-push-action@v2
          with:
            tags: localbuild/testimage:latest
            push: false
            load: true
            file: ${{ github.event.inputs.container-dockerfile }}" 

        - uses: anchore/scan-action@v3
          id: scan
          with:
            image: "localbuild/testimage:latest"
            fail-build: ${{ github.event.inputs.anchore-fail-build }}" 
            output-format: table

    semgrep-scan:
      if: ${{ github.event.inputs.sast-scan-flag }} == true
      name: Semgrep SAST scan
      runs-on: ubuntu-latest

      container:
      image: returntocorp/semgrep
      # Skip any PR created by dependabot to avoid permission issues:
      if: (github.actor != 'dependabot[bot]')
      steps:
        - uses: actions/checkout@v3
        - run: semgrep ci
          env:
            # Connect to Semgrep App through your SEMGREP_APP_TOKEN.
            # Generate a token from Semgrep App > Settings
            # and add it to your GitHub secrets.
            SEMGREP_APP_TOKEN: ${{ github.event.inputs.semgrep-app-token }}" 
            # Default timeout is 1800 seconds (30 minutes).
            # Set to 0 to disable the timeout.
            SEMGREP_TIMEOUT: ${{ github.event.inputs.semgrep-timeout }}" 