name: 'CI Security Checks'
description: 'A list of common open-source software security checks run as a composite Github action'
inputs:
  container-scan-flag:
    description: 'Enable anchore container image scanning'
    default: false
  container-dockerfile:
    description: 'Location of your dockerfile'
    default: ""
  anchore-results-file:
    description: 'The Anchore results file name and path'
    default: "results.json"
  anchore-severity-threshold:
    description: 'The Ancshore severitiy threshold you want to include in your report'
    default: "medium"
  anchore-fail-build:
    description: 'Fail build if severity threshold vulnerabilities are found'
    default: false
  sast-scan-flag:
    description: 'Enable Semgrep SAST scanning'
    default: true
  semgrep-app-token:
    description: 'You semgrep APP token taken from Semgrep App > Settings'
    default: ""
  semgrep-timeout:
    description: 'Scan timeout in seconds'
    default: 300
runs:
  using: "composite"
  steps:
    - name: Semgrep SAST Scan
      if: ${{ github.event.inputs.sast-scan-flag }} == true

    semgrep-scan:
      if: ${{ github.event.inputs.sast-scan-flag }} == true
      name: Semgrep SAST scan
      container:
        image: returntocorp/semgrep
      run: semgrep ci
      env:
        SEMGREP_APP_TOKEN: ${{ github.event.inputs.semgrep-app-token }}" 
        # Default timeout is 1800 seconds (30 minutes).
        # Set to 0 to disable the timeout.
        SEMGREP_TIMEOUT: ${{ github.event.inputs.semgrep-timeout }}" 

           