name: 'Dependency License Check'

on:
  workflow_call:
    inputs:
      dependency-check-config-file:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout dependency license check repository
        uses: chronograph-pe/checkout@v3
        with:
          repository: chronograph-pe/dependency-track-gh-action
          ref: main
          path: dependency-track-gh-action
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
              
      - name: Run dependency license check
        env:
          DEPENDENCY_CHECK_CONFIG: ${{ github.event.inputs.dependency-check-config-file }}
        run: | 
            echo "#### working dir! ###"
            echo `ls`
            echo "########"
            echo ${{ github.event.repository.name }}
            echo "repo name"
            echo ####
            pip install -r dependency-track-gh-action/requirements.txt
            python dependency-track-gh-action/app/main.py
            cat /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/job_summary.md >> $GITHUB_STEP_SUMMARY
            rm -rf dependency-track-gh-action
            rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/job_summary.md
            git pull origin ${{github.ref}} --ff-only

      - name: Commit license data to this branch
        uses: chronograph-pe/git-auto-commit-action@v4
