name: 'Dependency License Check'

on:
  workflow_call:
    inputs:
      dependency-check-config-file:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3

      - name: Checkout dependency license check repository
        uses: chronograph-pe/checkout@v3
        with:
          repository: chronograph-pe/dependency-track-gh-action
          ref: main
          path: dependency-track-gh-action
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
              
      - name: Run dependency license check
        env:
          DEPENDENCY_CHECK_CONFIG: ${{ github.event.inputs.dependency-check-config-file }}
        run: | 
            echo "#### working dir! ###"
            echo `ls`
            echo "### CD TO DEP ACTION ####"
            cd `dependency-track-gh-action`
            echo `ls`
