name: 'CI Security Checks'

on:
  workflow_call:
    secrets:
      semgrep-app-token:
        description: 'You semgrep APP token taken from Semgrep App > Settings'
        required: true
jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.semgrep-app-token }}
