name: 'CI Security Checks'
description: 'A list software security checks run as a composite Github action'

on:
  workflow_call:
    inputs:
      sast-scan-flag:
        description: 'Enable Semgrep SAST scanning'
        default: true
      semgrep-timeout:
        description: 'Scan timeout in seconds'
        default: 300
    secrets:
      semgrep-app-token:
        description: 'You semgrep APP token taken from Semgrep App > Settings'
        required: true
jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.semgrep-app-token }}
